language: node_js
cache: yarn

node_js:
  - "10.18.0"

jobs:
  include:
    - stage: test-lint
      name: "Test and Lint"
      script:
        - yarn run coverage
        - yarn run coveralls
      script: yarn run lint
      script: commitlint-travis
    - stage: build
      name: "Build package"
      script: yarn run build
    - stage: deploy
      name: "Deploy"
      if: branch = 'master' AND type != 'pull_request'
      script: yarn run deploy
    - stage: release
      name: "Release"
      #if: branch = 'master' AND type != 'pull_request'
      script: yarn semantic-release --dry-run
stages:
    - test-lint
    - build
    - deploy
    - release
