language: node_js
cache: yarn

node_js:
  - "10.4.0"

jobs:
  include:
    - stage: test-lint
      name: "Test and Lint"
      script:
        - yarn run coverage
        - yarn run coveralls
      script: yarn run lint
    - stage: build
      name: "Build package"
      script: yarn run build
    - stage: deploy
      name: "Deploy"
      if: branch = 'master' AND type != 'pull_request'
      script: yarn run deploy

stages:
    - test-lint
    - build
    - deploy
