language: node_js
cache: yarn

node_js:
  - "12.14.14"

jobs:
  include:
    - stage: test-lint
      name: "Test and Lint"
      script:
        - yarn run coverage
        - yarn run coveralls
      script: yarn run lint
      script: if [ $TRAVIS_BRANCH != "master" ]; then commitlint-travis; fi
    - stage: build
      name: "Build package"
      script: yarn run build
    - stage: deploy
      name: "Deploy"
      if: branch = 'master' AND type != 'pull_request'
      script: yarn run deploy
    - stage: release
      name: "Release"
      if: branch = 'master' AND type != 'pull_request'
      script: yarn run build && yarn semantic-release
stages:
    - test-lint
    - build
    - deploy
    - release
