language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - "8.10.0"
  - "10.4.0"

jobs:
  include:
    - stage: test-lint
      name: "Test and Lint"
      script:
        - yarn run test
        - yarn run lint
    - stage: build
      name: "Build package"
      script: yarn run build
    - stage: coveralls
      name: "Coveralls"
      script: yarn run coveralls
    - stage: deploy
      name: "Deploy"
      if: branch = 'master' AND type != 'pull_request'
      script: yarn run deploy

stages:
    - test-lint
    - build
    - coveralls
    - deploy
